<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Fixer\ArrayNotation;

use PhpCsFixer\AbstractFixer;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\Fixer\WhitespacesAwareFixerInterface;
use PhpCsFixer\FixerConfiguration\AllowedValueSubset;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Tokenizer\CT;
use PhpCsFixer\Tokenizer\Token;
use PhpCsFixer\Tokenizer\Tokens;

/**
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *  on_empty?: 'ensure_multiline'|'ensure_singleline'|'ignore',
 *  singleline_to_multiline?: list<'anonymous'|'destructure'|'property'|'return'|'variable'|'yield'>,
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *  on_empty: 'ensure_multiline'|'ensure_singleline'|'ignore',
 *  singleline_to_multiline: list<'anonymous'|'destructure'|'property'|'return'|'variable'|'yield'>,
 * }
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class MultilineArrayFormatFixer extends AbstractFixer implements WhitespacesAwareFixerInterface, ConfigurableFixerInterface
{
    /** @use ConfigurableFixerTrait<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration> */
    use ConfigurableFixerTrait;

    private const ARRAY_TYPE_ANONYMOUS = 'anonymous';
    private const ARRAY_TYPE_DESTRUCTURE = 'destructure';
    private const ARRAY_TYPE_VARIABLE = 'variable';
    private const ARRAY_TYPE_PROPERTY = 'property';
    private const ARRAY_TYPE_RETURN = 'return';
    private const ARRAY_TYPE_YIELD = 'yield';
    private const FORMAT_TYPE_IGNORE = 'ignore';
    private const FORMAT_TYPE_MULTILINE = 'multiline';
    private const FORMAT_TYPE_EMPTY_SINGLELINE = 'empty_singleline';

    private $configSinglelineToMultiline = [];
    private $array_opening_tags = [
        \T_ARRAY,
        \T_LIST,
        CT::T_ARRAY_SQUARE_BRACE_OPEN,
        CT::T_DESTRUCTURING_SQUARE_BRACE_OPEN,
    ];

    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'Defines how to handle arrays that contain line breaks.',
            [
                new CodeSample(
                    "<?php\n\$a = [1,\n    2, 3];\n",
                ),
                new CodeSample(
                    "<?php\n\$a = [1, 2, 3];\n",
                    ['singleline_to_multiline' => ['variable']],
                ),
            ],
        );
    }

    public function getConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder('singleline_to_multiline', 'Defines how to handle arrays that do not contain line breaks.'))
                ->setAllowedTypes(['string[]'])
                ->setAllowedValues([new AllowedValueSubset([
                    self::ARRAY_TYPE_ANONYMOUS,
                    self::ARRAY_TYPE_DESTRUCTURE,
                    self::ARRAY_TYPE_VARIABLE,
                    self::ARRAY_TYPE_PROPERTY,
                    self::ARRAY_TYPE_RETURN,
                    self::ARRAY_TYPE_YIELD,
                ])])
                ->setDefault([])
                ->getOption(),
            (new FixerOptionBuilder('on_empty', 'Defines how to handle arrays that do not contain any elements or comments.'))
                ->setAllowedValues(['ensure_multiline', 'ensure_singleline', 'ignore'])
                ->setDefault('ensure_singleline')
                ->getOption(),
        ]);
    }

    /**
     * {@inheritdoc}
     *
     * Must run before TrailingCommaInMultilineFixer, AlignMultilineCommentFixer, BinaryOperatorSpacesFixer.
     * Must run after MethodArgumentSpaceFixer.
     */
    public function getPriority(): int
    {
        return 28;
    }

    public function getName(): string
    {
        return 'multiline_array_format';
    }

    public function supports(\SplFileInfo $file): bool
    {
        return true;
    }

    public function isCandidate(Tokens $tokens): bool
    {
        return $tokens->isAnyTokenKindsFound($this->array_opening_tags);
    }

    protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder('singleline_to_multiline', 'Defines how to handle arrays that do not contain line breaks.'))
                ->setAllowedTypes(['string[]'])
                ->setAllowedValues([new AllowedValueSubset([
                    self::ARRAY_TYPE_ANONYMOUS,
                    self::ARRAY_TYPE_DESTRUCTURE,
                    self::ARRAY_TYPE_VARIABLE,
                    self::ARRAY_TYPE_PROPERTY,
                    self::ARRAY_TYPE_RETURN,
                    self::ARRAY_TYPE_YIELD,
                ])])
                ->setDefault([])
                ->getOption(),
            (new FixerOptionBuilder('on_empty', 'Defines how to handle arrays that do not contain any elements or comments.'))
                ->setAllowedValues(['ensure_multiline', 'ensure_singleline', 'ignore'])
                ->setDefault('ensure_singleline')
                ->getOption(),
        ]);
    }

    protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
    {
        // Set the config singleline_to_multiline to array keys for fast lookup
        $this->configSinglelineToMultiline = array_fill_keys($this->configuration['singleline_to_multiline'], true);

        for ($index = 0; $index < $tokens->count(); ++$index) {
            if ($this->isArrayOpenToken($tokens[$index])) {
                $index = $this->ensureArrayFormat($tokens, $index);
            }
        }
    }

    /**
     * Checks if the token is a possible opening for an array.
     */
    private function isArrayOpenToken(Token $token): bool
    {
        return $token->isGivenKind($this->array_opening_tags);
    }

    /**
     * Ensures the correct format for the array.
     *
     * @return int The updated index for the loop
     */
    private function ensureArrayFormat(Tokens $tokens, int $index): int
    {
        [$openIndex, $closeIndex] = $this->getArrayBounds($tokens, $index);

        if (null === $openIndex || null === $closeIndex) {
            return $index;
        }

        $formatType = $this->getFormatType($tokens, $openIndex, $closeIndex);

        switch ($formatType) {
            case self::FORMAT_TYPE_MULTILINE:
                return $this->ensureMultiline($tokens, $openIndex, $closeIndex);

            case self::FORMAT_TYPE_EMPTY_SINGLELINE:
                return $this->ensureEmptySingleline($tokens, $openIndex, $closeIndex);

            case self::FORMAT_TYPE_IGNORE:
                return $closeIndex;

            default:
                return $closeIndex;
        }
    }

    /**
     * Gets the format type based on the array type.
     */
    private function getFormatType(Tokens $tokens, int $openIndex, int $closeIndex): string
    {
        $isSingleline = true;
        $isEmpty = true;
        $arrayType = $this->getArrayType($tokens, $openIndex);
        $singlelineToMultiline = isset($this->configSinglelineToMultiline[$arrayType]);

        for ($index = $openIndex + 1; $index < $closeIndex; ++$index) {
            if ($this->isNewline($tokens[$index])) {
                $isSingleline = false;
            } elseif (!$tokens[$index]->isWhitespace()) {
                $isEmpty = false;
            }

            if (!$isEmpty && !$isSingleline) {
                return self::FORMAT_TYPE_MULTILINE;
            }
        }

        if ($isEmpty) {
            if ('ensure_singleline' === $this->configuration['on_empty']) {
                return self::FORMAT_TYPE_EMPTY_SINGLELINE;
            }
            if ('ensure_multiline' === $this->configuration['on_empty']) {
                return self::FORMAT_TYPE_MULTILINE;
            }

            return self::FORMAT_TYPE_IGNORE;
        }

        if ($singlelineToMultiline) {
            return self::FORMAT_TYPE_MULTILINE;
        }

        return self::FORMAT_TYPE_IGNORE;
    }

    /**
     * Gets the type of array from the previous meaningful token.
     */
    private function getArrayType(Tokens $tokens, int $index): string
    {
        if ($tokens[$index]->isGivenKind([
            \T_LIST,
            CT::T_DESTRUCTURING_SQUARE_BRACE_OPEN,
        ])) {
            return self::ARRAY_TYPE_DESTRUCTURE;
        }

        $prevMeaningful = $tokens->getPrevMeaningfulToken($index);
        $content = $tokens[$prevMeaningful]->getContent();

        switch ($content) {
            case '=':
                return self::ARRAY_TYPE_VARIABLE;

            case '=>':
                return self::ARRAY_TYPE_PROPERTY;

            case 'return':
                return self::ARRAY_TYPE_RETURN;

            case 'yield':
                return self::ARRAY_TYPE_YIELD;

            default:
                return self::ARRAY_TYPE_ANONYMOUS;
        }
    }

    /**
     * Ensures an empty array is on a single line with no spaces.
     */
    private function ensureEmptySingleline(Tokens $tokens, int $openIndex, int $closeIndex): int
    {
        $this->clearRange($tokens, $openIndex + 1, $closeIndex - 1);

        return $closeIndex;
    }

    /**
     * Ensures the multiline array is in the correct format.
     */
    private function ensureMultiline(Tokens $tokens, int $openIndex, int $closeIndex): int
    {
        [$baseLineEndIndent, $elementLineEndIndent] = $this->getLineEndIndents($tokens, $openIndex);

        // Insert new line indent after the opening tag
        $startIndex = $this->insertLineEndIndentAfter(
            $tokens,
            $openIndex,
            $closeIndex,
            $elementLineEndIndent,
        );

        // Loop through elements stop before the closing bracket
        for ($index = $startIndex; $index < $closeIndex - 1; ++$index) {
            // Handle nested arrays
            if ($this->isArrayOpenToken($tokens[$index])) {
                $oldCount = $tokens->count();
                $index = $this->ensureArrayFormat($tokens, $index);
                $closeIndex += $tokens->count() - $oldCount;

                continue;
            }

            // Insert new line indent after commas and comments
            if ($tokens[$index]->equals(',') || $tokens[$index]->isComment()) {
                if ($tokens->getNextMeaningfulToken($index) === $closeIndex) {
                    continue;
                }

                $index = $this->insertLineEndIndentAfter(
                    $tokens,
                    $index,
                    $closeIndex,
                    $elementLineEndIndent,
                );
            }
        }

        // Insert new line indent after the closing tag
        $this->insertLineEndIndentBefore(
            $tokens,
            $closeIndex,
            $closeIndex,
            $baseLineEndIndent,
        );

        return $closeIndex;
    }

    /**
     * Inserts the new line and indent after a specified index.
     *
     * @return int The updated index for the loop
     */
    private function insertLineEndIndentAfter(Tokens $tokens, int $index, int &$closeIndex, string $lineEndIndent): int
    {
        $targetIndex = $index + 1;

        if (!$tokens[$targetIndex]->isWhitespace() && !$tokens[$targetIndex]->isGivenKind(\T_COMMENT)) {
            $this->insertAt($tokens, $targetIndex, \T_WHITESPACE, $lineEndIndent);
            ++$closeIndex;

            return $targetIndex + 1;
        }

        $nextMeaningful = $tokens->getNextMeaningfulToken($targetIndex);
        $inlineComments = $this->findInlineComments($tokens, $targetIndex, $nextMeaningful);

        if ($inlineComments) {
            $targetIndex = end($inlineComments) + 1;
        }

        if ($tokens[$targetIndex]->isWhitespace()) {
            $this->replaceAt($tokens, $targetIndex, \T_WHITESPACE, $lineEndIndent);
        } else {
            $this->insertAt($tokens, $targetIndex, \T_WHITESPACE, $lineEndIndent);
            ++$closeIndex;
        }

        $nextNonWhitespace = $tokens->getTokenNotOfKindsSibling(
            $targetIndex,
            1,
            [\T_WHITESPACE],
        );

        $this->clearRange($tokens, $targetIndex + 1, $nextNonWhitespace - 1);

        return $nextNonWhitespace - 1;
    }

    /**
     * Inserts the new line and indent before a specified index.
     *
     * @return int The updated index for the loop
     */
    private function insertLineEndIndentBefore(Tokens $tokens, int $index, int &$closeIndex, string $lineEndIndent): int
    {
        $targetIndex = $index - 1;

        if (!$tokens[$targetIndex]->isWhitespace()) {
            $this->insertAt($tokens, $index, \T_WHITESPACE, $lineEndIndent);
            ++$closeIndex;

            return $index + 1;
        }

        $this->replaceAt($tokens, $targetIndex, \T_WHITESPACE, $lineEndIndent);

        $prevNonWhitespace = $tokens->getTokenNotOfKindsSibling(
            $targetIndex,
            -1,
            [\T_WHITESPACE],
        );

        $this->clearRange($tokens, $prevNonWhitespace + 1, $targetIndex - 1);

        return $index;
    }

    /**
     * Clears all tokens in a range. Optionally skip indexes.
     */
    private function clearRange(Tokens $tokens, int $start, int $end, array $exclude = []): void
    {
        for ($index = $start; $index <= $end; ++$index) {
            if ($exclude && \in_array($index, $exclude, true)) {
                continue;
            }
            $tokens->clearAt($index);
        }
    }

    /**
     * Replaces a token at an index.
     */
    private function replaceAt(Tokens $tokens, int $index, int $key, string $content, string $debug_key = ''): void
    {
        if ($tokens[$index]->getContent() === $content) {
            return;
        }

        $tokens[$index] = new Token([$key, $content]);
    }

    /**
     * Inserts a token at an index.
     */
    private function insertAt(Tokens $tokens, int $index, int $key, string $content, string $debug_key = ''): void
    {
        if ($tokens[$index]->getContent() === $content) {
            return;
        }

        $tokens->insertAt($index, new Token([$key, $content]));
    }

    /**
     * Checks if there is a comment immediately after the given index before any meaningful or \n characters.
     *
     * @returns ?array
     */
    private function findInlineComments(Tokens $tokens, int $start, int $end): ?array
    {
        $indexes = [];

        for ($index = $start; $index < $end; ++$index) {
            $token = $tokens[$index];

            if ($token->isGivenKind(\T_COMMENT)) {
                $indexes[] = $index;

                continue;
            }

            if (!$token->isWhitespace() || $this->isNewline($token)) {
                break;
            }
        }

        return \count($indexes) ? $indexes : null;
    }

    /**
     * Gets the opening and ending index for the array.
     *
     * @returns ?array
     */
    private function getArrayBounds(Tokens $tokens, int $openIndex): ?array
    {
        if ($tokens[$openIndex]->isGivenKind(CT::T_ARRAY_SQUARE_BRACE_OPEN)) {
            return [
                $openIndex,
                $tokens->findBlockEnd(
                    Tokens::BLOCK_TYPE_ARRAY_SQUARE_BRACE,
                    $openIndex,
                ),
            ];
        }
        if ($tokens[$openIndex]->isGivenKind(CT::T_DESTRUCTURING_SQUARE_BRACE_OPEN)) {
            return [
                $openIndex,
                $tokens->findBlockEnd(
                    Tokens::BLOCK_TYPE_DESTRUCTURING_SQUARE_BRACE,
                    $openIndex,
                ),
            ];
        }
        if ($tokens[$openIndex]->isGivenKind([\T_ARRAY, \T_LIST])) {
            $startIdx = $tokens->getNextTokenOfKind($openIndex, ['(']);
            if (null === $startIdx) {
                return null;
            }

            return [
                $startIdx,
                $tokens->findBlockEnd(
                    Tokens::BLOCK_TYPE_PARENTHESIS_BRACE,
                    $startIdx,
                ),
            ];
        }

        return null;
    }

    /**
     * Get the line end plus indent strings for both base and elements.
     *
     * @return array {0: string, 1: string} baseLineEndIndent, elementLineEndIndent
     */
    private function getLineEndIndents(Tokens $tokens, int $openIndex): array
    {
        $baseIndent = $this->getBaseIndent($tokens, $openIndex);
        $elementIndent = $baseIndent.$this->whitespacesConfig->getIndent();
        $lineEnd = $this->whitespacesConfig->getLineEnding();

        $baseLineEndIndent = $lineEnd.$baseIndent;
        $elementLineEndIndent = $lineEnd.$elementIndent;

        return [$baseLineEndIndent, $elementLineEndIndent];
    }

    /**
     * Gets the already indented space before the opening bracket.
     *
     * This function is derived the beginging of
     * PhpCsFixer\Fixer\FunctionNotation::ensureFunctionFullyMultiline
     */
    private function getBaseIndent(Tokens $tokens, int $openIndex): string
    {
        $searchIndex = $openIndex;

        do {
            $prevWhitespaceTokenIndex = $tokens->getPrevTokenOfKind(
                $searchIndex,
                [[\T_ENCAPSED_AND_WHITESPACE], [\T_INLINE_HTML], [\T_WHITESPACE]],
            );

            $searchIndex = $prevWhitespaceTokenIndex;
        } while (null !== $prevWhitespaceTokenIndex
            && !str_contains($tokens[$prevWhitespaceTokenIndex]->getContent(), "\n")
        );

        if (null === $prevWhitespaceTokenIndex) {
            $existingIndentation = '';
        } elseif (!$tokens[$prevWhitespaceTokenIndex]->isGivenKind(\T_WHITESPACE)) {
            return '';
        } else {
            $existingIndentation = $tokens[$prevWhitespaceTokenIndex]->getContent();
            $lastLineIndex = strrpos($existingIndentation, "\n");
            $existingIndentation = false === $lastLineIndex
                ? $existingIndentation
                : substr($existingIndentation, $lastLineIndex + 1);
        }

        return $existingIndentation;
    }

    /**
     * Checks if a token is a new line character.
     */
    private function isNewline(Token $token): bool
    {
        return $token->isWhitespace() && str_contains($token->getContent(), "\n");
    }
}
