<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Tests\Fixer\ArrayNotation;

use PhpCsFixer\Tests\Test\AbstractFixerTestCase;

/**
 * @internal
 *
 * @covers \PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFormatFixer
 *
 * @extends AbstractFixerTestCase<\PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFormatFixer>
 *
 * @phpstan-import-type _AutogeneratedInputConfiguration from \PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFormatFixer
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class MultilineArrayFormatFixerTest extends AbstractFixerTestCase
{
    /**
     * @dataProvider provideFixCases
     */
    public function testFix(string $expected, ?string $input = null, ?array $config = null): void
    {
        if ($config) {
            $this->fixer->configure($config);
        }

        $this->doTest($expected, $input);
    }

    public static function provideFixCases(): iterable
    {
        // default config
        yield 'Single line array remains untouched.' => [
            '<?php
$arr = [ 1, 2, 3 ];',
        ];

        yield 'Single line nested array remains untouched.' => [
            '<?php
$arr = [ "one" => [ 1, 2 ] ];',
        ];

        yield 'Multiline array gets formatted.' => [
            '<?php
$arr = [
    1,
    2,
    3
];',
            '<?php
$arr = [1, 2, 3
            ];',
        ];

        yield 'Multiline nested array gets formatted.' => [
            '<?php
$arr = [
    1,
    2,
    3 => [
        "one" => 1
    ]
];',
            '<?php
$arr = [1, 2, 3 => [
            "one" => 1 ]
            ];',
        ];

        yield 'Multiline nested array with siblings gets formatted.' => [
            '<?php
$arr = [
    "a" => [
        "a_1" => "val_a"
    ],
    "b" => [
        "b_1" => "val_b"
    ],
    "c" => [
        "c_1" => "val_c"
    ]
];',
            '<?php
$arr = [
    "a" => [ "a_1" => "val_a"
],
"b" => [
        "b_1" => "val_b" ],
                "c" => [
                    "c_1" => "val_c" ]
];',
        ];

        yield 'Multiline deeply nested array gets formatted.' => [
            '<?php
$arr = [
    "level_1" => [
        "level_2" => [
            "level_3" => [
                "level_4" => [
                    "level_5" => [
                        "level_6" => [
                            "level_7" => [
                                "level_8" => [
                                    "level_9" => [
                                        "level_10" => [
                                            "deep_value" => "You found me!",
                                            "deep_array" => [1, 2, 3, 4, 5],
                                            "deep_assoc" => ["key" => "value"],
                                            "deep_bool" => true,
                                            "deep_null" => null,
                                            "deep_float" => 3.14159
                                        ]
                                    ]
                                ]
                            ],
                            "branch_a" => [
                                "sub_branch_1" => [
                                    "sub_sub_1" => [
                                        "data" => "nested data 1",
                                        "number" => 42,
                                        "active" => true,
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];',
            '<?php
$arr = [
    "level_1" => [
      "level_2" => [
    "level_3" => [
        "level_4" => [
      "level_5" => [
            "level_6" => [
          "level_7" => [
        "level_8" => [
            "level_9" => [
          "level_10" => [
                "deep_value" => "You found me!",
            "deep_array" => [1, 2, 3, 4, 5],
                "deep_assoc" => ["key" => "value"],
              "deep_bool" => true,
                "deep_null" => null,
              "deep_float" => 3.14159
          ]
            ]
        ]
          ],
  "branch_a" => [
            "sub_branch_1" => [
          "sub_sub_1" => [
                "data" => "nested data 1",
              "number" => 42,
"active" => true,
],
],
],
],
],
],
],
],
],
];',
        ];

        yield 'Long syntax array gets formatted.' => [
            '<?php
$arr = array(
    "one",
    "two" => array( "one" )
);',
            '<?php
$arr = array( "one",
            "two" => array( "one" ));',
        ];

        yield 'Long syntax nested array gets formatted with on_singleline = ensure_fully_multiline.' => [
            '<?php
$arr = array(
    "one",
    "two" => array(
        "one"
    ),
);',
            '<?php
$arr = array( "one",
            "two" => array( "one" ),);',
            ['on_singleline' => 'ensure_fully_multiline'],
        ];
    }
}
